### ISSUE TITLE
Talk: Amazon API Gateway + AWS Lambda

### ISSUE THREAD

**Issue by chadbrewbaker** [DevOpsDSM/devopsdsm#14]
Introduction to shut up and take my money ops. How to build, test, and deploy managed REST applications on AWS.

**Comment by sherzberg** [comment]
@chadbrewbaker can you start a discussion on Lambda and API Gateway this week? Maybe a demo and talk about how they both work separately and together? Maybe plan on a demo for 20-30 minutes and we can have a discussion for the rest of the time?

Thoughts?

**Comment by chadbrewbaker** [comment]
Not on two days notice, first week kids are in school etc :)  I'll see if I can throw a few hours at it on Tuesday night. I agreed to give an AWS Lambda talk to CIALUG for next month's meeting so I should definitely have something by then.

This month might be better to walk through the Hashicorp stack and some AWS basics? https://github.com/hashicorp/terraform/tree/master/examples/aws-two-tier 
http://docs.aws.amazon.com/IAM/latest/UserGuide/introduction.html
https://chadthompson.me/2013/05/static-web-hosting-with-amazon-s3/

**Comment by sherzberg** [comment]
@chadbrewbaker ok no worries! a bunch of us just went to MesosCon so maybe we will do a recap.

**Comment by chadbrewbaker** [comment]
Closed.

**Comment by sherzberg** [comment]
Closed with https://github.com/DevOpsDSM/devopsdsm/pull/16
