### ISSUE TITLE
AWS Lambda Intro and Discussion

### ISSUE THREAD

**Issue by jeremydwitte-zz** [DevOpsDSM/devopsdsm#17]
I saw that you are going to be presenting an AWS Lambda Intro and Discussion for the next DevOpsDSM - very excited! Would love to chat with you about opening this event up to the AWS group for those interested in Lambda. I think this would be a great opportunity for members of both groups to extend their community and interests.  

I can also be reached at jeremy.witte@mittera.com  

Regards 
Jeremy

**Comment by sherzberg** [comment]
Hi @jeremywitte. I'm curious what you would like to do to open this up to the AWS group? Do you want to just announce that we are having an AWS Lambda intro? Have any idea how many would be interested in coming that don't normally attend our group?

**Comment by jeremydwitte-zz** [comment]
Hi Spencer,

I was thinking this would be a great event to post to the AWS group and make it aware to them.  I know we have a developer that has been playing with Lamba a bit and I’m sure there are others interested as well.  I would expect 8-12 users that would potentially show up in addition to those already attending your group.  There are already a few members part of both groups that would also cancel out a few numbers of those that would RSVP on the AWS group page.

I want to make sure this is OK with you and your group before posting and making aware to the AWS user group.

Thanks

JEREMY WITTE | IT Director
1312 Locust Street Suite 202 | Des Moines, IA 50309
o. 515.343.5341 | c. 515.868.7209
jeremy.witte@mittera.commailto:jeremy.witte@mittera.com

On Sep 21, 2015, at 9:47 AM, Spencer Herzberg <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi @jeremywittehttps://github.com/jeremywitte. I'm curious what you would like to do to open this up to the AWS group? Do you want to just announce that we are having an AWS Lambda intro? Have any idea how many would be interested in coming that don't normally attend our group?

—
Reply to this email directly or view it on GitHubhttps://github.com/DevOpsDSM/devopsdsm/issues/17#issuecomment-142004536.

[Mittera Group]http://mitteragroup.com
MITTERA GROUP is a multi-platform communications company with more than 750 professionals who provide quality printing, direct mail, analytics, design and digital solutions for clients throughout the U.S.
CONFIDENTIALITY NOTICE: This e-mail message is intended only for the use of the individual or entity to which it is addressed and may contain information that is privileged, confidential and exempt from disclosure under applicable law. If you are not the intended recipient, any dissemination, distribution or copying of this communication is strictly prohibited. If you have received this communication in error, please do not distribute it. Please notify the sender by e-mail at the address shown and delete or destroy the original message and any attachments. Thank you.

**Comment by sherzberg** [comment]
Awesome. I think this would be fine to announce it. The more the merrier. I will let the sponsor know that they should plan on a few more then.

cc @chadbrewbaker see above ;)

Thanks!

**Comment by jeremydwitte-zz** [comment]
Thanks Spencer - see you there!

JEREMY WITTE | IT Director
1312 Locust Street Suite 202 | Des Moines, IA 50309
o. 515.343.5341 | c. 515.868.7209
jeremy.witte@mittera.commailto:jeremy.witte@mittera.com

On Sep 21, 2015, at 10:56 AM, Spencer Herzberg <notifications@github.com<mailto:notifications@github.com>> wrote:

Awesome. I think this would be fine to announce it. The more the merrier. I will let the sponsor know that they should plan on a few more then.

cc @chadbrewbakerhttps://github.com/chadbrewbaker see above ;)

Thanks!

—
Reply to this email directly or view it on GitHubhttps://github.com/DevOpsDSM/devopsdsm/issues/17#issuecomment-142025858.

[Mittera Group]http://mitteragroup.com
MITTERA GROUP is a multi-platform communications company with more than 750 professionals who provide quality printing, direct mail, analytics, design and digital solutions for clients throughout the U.S.
CONFIDENTIALITY NOTICE: This e-mail message is intended only for the use of the individual or entity to which it is addressed and may contain information that is privileged, confidential and exempt from disclosure under applicable law. If you are not the intended recipient, any dissemination, distribution or copying of this communication is strictly prohibited. If you have received this communication in error, please do not distribute it. Please notify the sender by e-mail at the address shown and delete or destroy the original message and any attachments. Thank you.

**Comment by chadbrewbaker** [comment]
Can close this.
