### ISSUE TITLE
Talk / Discussion: Continuous Delivery

### ISSUE THREAD

**Issue by lamdor** [DevOpsDSM/devopsdsm#19]
We should talk about the different ways that we approach continuous delivery and the pros/cons of that.

**Comment by sherzberg** [comment]
Would you like to lead this? If so, can you send a PR for a future meeting date with the details?

**Comment by lamdor** [comment]
@sherzberg Will do.

**Comment by sherzberg** [comment]
@rubbish any chance u are willing and able to do this this month (27th)?

**Comment by lamdor** [comment]
@sherzberg Sure, I'd be able to lead a discussion on it and talk about how we approach it.

**Comment by sherzberg** [comment]
@rubbish sweet! Can you put up a PR for the topic intro sometime this week so I can start sending reminders and such?

**Comment by lamdor** [comment]
@sherzberg yep. will do that later today.

**Comment by sherzberg** [comment]
@rubbish any chance I can get the intro early this week? Pretty Please? Otherwise I will make one up and we nobody wants that.

**Comment by lamdor** [comment]
I'll get one done today.

Luke
