### ISSUE TITLE
Talk: Jenkins 2.0

### ISSUE THREAD

**Issue by lamdor** [DevOpsDSM/devopsdsm#23]
There's a lot of new features that will be in Jenkins 2.0 (https://wiki.jenkins-ci.org/display/JENKINS/Jenkins+2.0) like `Jenkinsfile`s and Pipeline as first class citizen: https://wiki.jenkins-ci.org/display/JENKINS/2.0+Pipeline+as+Code

It'd be great once Jenkins 2.0 is out (probably here in the next month) to do a quick talk on some of the new features.

I probably could do this, just need to research it a bit.

**Comment by sherzberg** [comment]
`Jenkinsfile` is worth the talk alone. I have wanted this for a very long time as similar things exist in other ci platforms like `drone.io`, `travis-ci`, and `werker`. April is open :)

**Comment by sherzberg** [comment]
Closed via https://github.com/DevOpsDSM/devopsdsm/issues/28
