### ISSUE TITLE
TALK: Continuous Deployment with Jenkins Pipeline

### ISSUE THREAD

**Issue by lamdor** [DevOpsDSM/devopsdsm#28]
Closes #23

## Description

Over a year ago, I did a presentation here at the DevOpsDSM about Continuous Delivery. At the time, I said _Maybe the new work going on with Jenkins Pipelines will help..._ Well, after implementing them for us at Banno/Jack Henry, I can definitively say that it has helped. 

Jenkins Pipelines are a set of Jenkins jobs and plugins on steroids with the power of a Groovy DSL to mix it all together. It allows one to model a simple to a very complex continuous delivery pipeline as code and checked in with the source code itself.

I'll go through how to use a Jenkinsfile from scratch all the way through deploying a Github project across environments using Kubernetes. Along the way, I'll go over some of the gotcha's and breakthroughs that we've learned while implementing this for our banking products.

**Comment by sherzberg** [comment]
Thank your Sir! Website updated: http://devopsdsm.com/posts/ci-jenkinsfile
