### ISSUE TITLE
slack preview icon

### ISSUE THREAD

**Issue by darrinholst** [DevOpsDSM/devopsdsm#29]
<img width="230" alt="slack_-_lean_techniques" src="https://cloud.githubusercontent.com/assets/4854/24468175/09f80e52-147d-11e7-897d-2de31946ea6e.png">

Noticed that holman's avatar is showing up in the slack preview of a url. Must be pulling it from the [apple-touch-icon](https://github.com/DevOpsDSM/devopsdsm/blob/gh-pages/apple-touch-icon.png) which is probably not what you want. Unless it is which, in that case, is kind of weird.

**Comment by sherzberg** [comment]
Kind of a running joke when we set up the theme for the website. It was just included in the theme and we never changed it. We should probably change it now though...
