### ISSUE TITLE
Talk Ideas

### ISSUE THREAD

**Issue by adamdecaf** [DevOpsDSM/devopsdsm#5]
Thinking out loud here. Feel free to add more here. 
- Setting up a realistic dev environment in vagrant.
- Docker intro (api + db + lb) setup
- How to better manage secrets?

**Comment by sherzberg** [comment]
@adamdecaf sweet! can you split these out into individual gh issues? these could each be 1hr topics!

**Comment by adamdecaf** [comment]
Sure!
