### ISSUE TITLE
Talk: How to better manage secrets?

### ISSUE THREAD

**Issue by adamdecaf** [DevOpsDSM/devopsdsm#8]
We all commit them into source control, but that's a very high risk operation. There are some tools out there that try and help out the problem, but how can they actually be used?
- https://github.com/square/keywhiz
- https://github.com/hashicorp/vault
- https://www.gnupg.org/

**Comment by chadothompson** [comment]
^^^ This is a fascinating topic and one that I've kind of struggled with myself.

**Comment by sherzberg** [comment]
For lack of time for this months meeting, anyone have any objections to me starting a discussion on secrets? I can talk about the direction Banno is taking and we can talk through what everyone else is doing?

**Comment by adamdecaf** [comment]
@sherzberg That sound good to me!
